### ISSUE TITLE
OSGi has standardized weaving in 4.3

### ISSUE THREAD

**Issue by pkriens** [andreyvit/kilim-osgi#1]
In release 4.3 the OSGi Alliance has specified a weaving service that would be very suitable, and Eclipse supports it as well. Using this service would make this generally available. If you adapt your code and could provide me we an example bundle that leverages this then I'd love to write a blog about his on the OSGi web site.

Peter Kriens

**Comment by andreyvit** [comment]
Closing due to lack of interest for 6 years. :-)
